#!/bin/sh
#
# Copyright (c) 2010, 2011 CloudFlare, Inc. (http://www.cloudflare.com)
# Copyright (c) 2010, 2011 Matthieu Tourne <matthieu.tourne@gmail.com>
#
# @author Matthieu Tourne <matthieu@cloudflare.com>
#

ngx_addon_name=ngx_http_instaweb_module

HTTP_AUX_FILTER_MODULES="$HTTP_AUX_FILTER_MODULES ngx_http_instaweb_module"

PAGESPEED_ROOT="/mnt/hgfs/vm_share/tmp/pagespeed/mod_pagespeed"

PAGESPEED_BUILDMODE="Debug"

PAGESPEED_INCS="\
  $PAGESPEED_ROOT/src/
  $PAGESPEED_ROOT/src/third_party/base64 \
  $PAGESPEED_ROOT/src/third_party/chromium/src \
  $PAGESPEED_ROOT/src/third_party/google-sparsehash/src \
  $PAGESPEED_ROOT/src/third_party/google-sparsehash/gen/arch/linux/x64/include \
  $PAGESPEED_ROOT/src/third_party/libpagespeed/src \
  $PAGESPEED_ROOT/src/third_party/protobuf/ \
  $PAGESPEED_ROOT/src/third_party/protobuf/src/ \
  "

PAGESPEED_SRCS="\
  $PAGESPEED_ROOT/src/net/instaweb/htmlparse \
  $PAGESPEED_ROOT/src/third_party/chromium \
  $PAGESPEED_ROOT/src/third_party/google-sparsehash \
  "

CFLAGS=`echo $CFLAGS | sed -e 's/-Werror//'`
echo "CFLAGS: $CFLAGS"

test_output() {
   if [ $1 -ne "0" ]; then
      exit 1
   fi
}

CORE_INCS="$CORE_INCS \
  $ngx_addon_dir/libs \
  $PAGESPEED_INCS \
  "
#  $ngx_addon_dir/libs \

# create protoc output dirs

CURDIR=`pwd`

PROTOC_BIN="$PAGESPEED_ROOT/src/out/$PAGESPEED_BUILDMODE/protoc"

cd $PAGESPEED_ROOT/src/net/instaweb && \
    $PROTOC_BIN --proto_path="../.." \
    "../../net/instaweb/http/http.proto" \
    --cpp_out="$ngx_addon_dir/libs/"

test_output $?

cd $PAGESPEED_ROOT/src/net/instaweb && \
    $PROTOC_BIN --proto_path="../.." \
    "../../net/instaweb/rewriter/cached_result.proto" \
    --cpp_out="$ngx_addon_dir/libs/"

test_output $?

cd $PAGESPEED_ROOT/src/net/instaweb && \
    $PROTOC_BIN --proto_path="../.." \
    "../../net/instaweb/spriter/public/image_spriter.proto" \
    --cpp_out="$ngx_addon_dir/libs/"

test_output $?

cd $CURDIR

NGX_ADDON_DEPS="$NGX_ADDON_DEPS \
  $ngx_addon_dir/ngx_http_instaweb_module.h \
  $ngx_addon_dir/ngx_message_handler.h \
  $ngx_addon_dir/libs/net/instaweb/http/http.pb.h \
  $ngx_addon_dir/libs/net/instaweb/rewriter/cached_result.pb.h \
  $ngx_addon_dir/libs/net/instaweb/spriter/public/image_spriter.pb.h \
  $ngx_addon_dir/ngx_http_instaweb_filter.h \
  $ngx_addon_dir/ngx_filter_driver.h \
  $ngx_addon_dir/ngx_pagespeed_writer.h \
  "

NGX_ADDON_SRCS="$NGX_ADDON_SRCS \
	$ngx_addon_dir/ngx_http_instaweb_module.cpp \
        $ngx_addon_dir/ngx_message_handler.cpp \
        $ngx_addon_dir/libs/net/instaweb/http/http.pb.cc \
        $ngx_addon_dir/libs/net/instaweb/rewriter/cached_result.pb.cc
        $ngx_addon_dir/libs/net/instaweb/spriter/public/image_spriter.pb.cc \
	$ngx_addon_dir/ngx_http_instaweb_filter.cpp \
	$ngx_addon_dir/ngx_filter_driver.cpp \
	$ngx_addon_dir/ngx_pagespeed_writer.cpp \
        "


CORE_LIBS="$CORE_LIBS -lstdc++ -Wl,-z,noexecstack -lrt"

PWD=$ngx_addon_dir/libs make BUILDTYPE=$PAGESPEED_BUILDMODE -C $PAGESPEED_ROOT/src/net/instaweb/automatic exe

CORE_LIBS="$CORE_LIBS \
  $ngx_addon_dir/libs/pagespeed_automatic.a
  "

echo "libs included:"
echo $CORE_LIBS
